default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 4SuTnBOnZCMsVZLTZ9pOK4UEHRs5csjDGrW5FrEVfsZ91gQiHjT0uvcER8tcVcPX
  host: 172.19.0.6
  port: 5432

development:
  <<: *default
  database: blog52_development
test:
  <<: *default
  database: blog52_development
production:
  <<: *default
  database: blog52_prod
