default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: <%= ENV["WEB_DB_PASSWORD"] %>
  host: <%= ENV["DB_HOST"] %>
  port: 5432

development:
  adapter: postgresql
  encoding: unicode
  database: blog_development
  pool: 5
  username: postgres
  password: "12345"
  host: localhost
test:
  <<: *default
  database: blog52_development
production:
  <<: *default
  database: blog52_prod
